In [47]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

In [48]:
x = np.array([[1], [2], [3]])

features = PolynomialFeatures(degree=3)
features.fit(x)
x_transformed = features.transform(x)

print(x_transformed)

np.random.seed(0)
print(np.random.default_rng().normal(-3, 3, 20))

[[ 1.  1.  1.  1.]
 [ 1.  2.  4.  8.]
 [ 1.  3.  9. 27.]]
[-6.00196309 -6.35731628 -6.20997245  1.02188452 -3.42312273 -3.91387751
 -3.64616065 -4.22858452 -1.57792714 -4.4717559   0.36586053 -1.44803987
 -6.16285677 -7.92496751 -4.27430034 -7.16328778  1.11066135 -1.88339543
 -6.79606755 -8.7542053 ]
